### ISSUE TITLE
insiM error

### ISSUE THREAD

**Issue by asmmahmoud** [thesushantpatil/insiM#1]
Hi, 
I am trying to use insiM but it just runs for few seconds and gave me this error "  File "insiM-master/insiM_v1.0.py", line 326, in main
    REF = genome[mutation_chrom][(mutation_start-1):(mutation_start+indellen)]
KeyError: 'chr1'

This is from the log file 
insiM initiated.

############################
Parsing the configuration file ...
Parsing the target bed file for format check ...
Reading in genome FASTA file ...
Merging chromosomes into strings for final genome dict ...
Opening input and output files...
Reading in bed entries...
        76 bed entries recorded.
Determining mutation locations based on bed file entry mid-points...
Working on chr1 ...

Any idea how to solve this error ?
Thank you

**Comment by thesushantpatil** [comment]
Hi Asmaa,

Thank you for your interest in insiM. 

Upon looking at the files you shared with me, it was found that this error was caused by the genome FASTA file with additional fields on the ">chr#" line e.g. -
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38

The latest version of insiM (v1.1) is updated to handle this along with a few other, minor improvements.
